package com.hwb.aianswerer.ui.pages.models

import androidx.compose.ui.graphics.Color

// =============================================================================
// Data Models
// =============================================================================
enum class ModelProviderType(val label: String, val color: Color) {
    OPENAI("OpenAI 兼容", Color(0xFF34C759)),
    ANTHROPIC("Anthropic", Color(0xFFD4A853)),
    GEMINI("Gemini", Color(0xFF4A90D9)),
    OLLAMA("Ollama", Color(0xFF9E9E9E)),
    AZURE("Azure", Color(0xFF0078D4)),
    CUSTOM("自定义", Color(0xFF9B8FF8))
}

data class ProviderDef(
    val id: String, val name: String, val type: ModelProviderType,
    val apiHost: String, val availableModels: List<String> = listOf(),
    val officialUrl: String? = null, val apiKeyUrl: String? = null
)

data class ProviderState(
    val def: ProviderDef,
    var apiKey: String = "", var customHost: String = "",
    var enabled: Boolean = false, var selectedModels: List<String> = listOf()
)

// Whitelist update state
internal sealed class WhitelistUpdateState {
    data object Idle : WhitelistUpdateState()
    data object Checking : WhitelistUpdateState()
    data class Success(
        val visionCount: Int,
        val excludedCount: Int,
        val totalCount: Int,
        val languageCount: Int,
        val providerCount: Int,
        val newProviderCount: Int,
        val newModelCount: Int
    ) : WhitelistUpdateState()
    data class Fail(val msg: String) : WhitelistUpdateState()
}

// =============================================================================
// Provider Definitions
// 国内常用提供者放在前面，方便用户选择
// =============================================================================
internal val MODEL_PROVIDERS = listOf(
    // 自定义提供者（置顶）
    ProviderDef("custom", "自定义 OpenAI 兼容", ModelProviderType.CUSTOM, "", listOf(), null, null),
    // 国内常用提供者
    ProviderDef("deepseek", "DeepSeek", ModelProviderType.OPENAI, "https://api.deepseek.com/v1",
        listOf("deepseek-chat", "deepseek-reasoner"),
        "https://deepseek.com", "https://platform.deepseek.com/api_keys"),
    ProviderDef("dashscope", "阿里百炼", ModelProviderType.OPENAI, "https://dashscope.aliyuncs.com/compatible-mode/v1",
        listOf("qwen-max", "qwen-plus", "qwen-turbo", "qwen-vl-max", "qwen-vl-plus"),
        "https://tongyi.aliyun.com", "https://dashscope.console.aliyun.com/apiKey"),
    ProviderDef("zhipu", "智谱清言", ModelProviderType.OPENAI, "https://open.bigmodel.cn/api/paas/v4",
        listOf("glm-4-plus", "glm-4-flash", "glm-4-long", "glm-4v"),
        "https://open.bigmodel.cn", "https://open.bigmodel.cn/usercenter/apikeys"),
    ProviderDef("moonshot", "Kimi", ModelProviderType.OPENAI, "https://api.moonshot.cn/v1",
        listOf("moonshot-v1-128k", "moonshot-v1-32k", "moonshot-v1-8k"),
        "https://moonshot.cn", "https://platform.moonshot.cn/console/api-keys"),
    ProviderDef("mimo", "MiMo", ModelProviderType.OPENAI, "https://api.xiaomi.com/v1",
        listOf("mimo-v2-flash", "mimo-v2-pro", "mimo-v2.5"),
        "https://mimo.xiaomi.com", "https://mimo.xiaomi.com/api-keys"),
    ProviderDef("silicon", "硅基流动", ModelProviderType.OPENAI, "https://api.siliconflow.cn/v1",
        listOf("Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V3", "THUDM/glm-4-9b-chat"),
        "https://siliconflow.cn", "https://cloud.siliconflow.cn/account/ak"),
    // 国际提供者
    ProviderDef("openai", "OpenAI", ModelProviderType.OPENAI, "https://api.openai.com/v1",
        listOf("gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o1", "o3-mini"),
        "https://openai.com", "https://platform.openai.com/api-keys"),
    ProviderDef("anthropic", "Anthropic", ModelProviderType.ANTHROPIC, "https://api.anthropic.com/v1",
        listOf("claude-sonnet-4-20250514", "claude-opus-4-20250514", "claude-haiku-4-5-20251001", "claude-3-5-sonnet-20241022"),
        "https://anthropic.com", "https://console.anthropic.com/settings/keys"),
    ProviderDef("gemini", "Google Gemini", ModelProviderType.GEMINI, "https://generativelanguage.googleapis.com/v1beta",
        listOf("gemini-2.0-flash", "gemini-2.5-pro", "gemini-1.5-pro"),
        "https://gemini.google.com", "https://aistudio.google.com/apikey"),
    ProviderDef("openrouter", "OpenRouter", ModelProviderType.OPENAI, "https://openrouter.ai/api/v1",
        listOf("anthropic/claude-sonnet-4", "google/gemini-2.5-pro", "deepseek/deepseek-chat-v3-0324"),
        "https://openrouter.ai", "https://openrouter.ai/settings/keys"),
    ProviderDef("ollama", "Ollama (本地)", ModelProviderType.OLLAMA, "http://localhost:11434/v1",
        listOf("llama3.1", "qwen2.5", "deepseek-r1", "llava", "minicpm-v"),
        "https://ollama.com"),
    ProviderDef("azure-openai", "Azure OpenAI", ModelProviderType.AZURE,
        "https://{resource}.openai.azure.com/openai/deployments/{deployment}",
        listOf("gpt-4o", "gpt-4", "gpt-35-turbo"),
        "https://azure.microsoft.com/products/ai-services/openai-service"),
    // 更多国内常用厂商
    ProviderDef("minimax", "MiniMax (海螺)", ModelProviderType.OPENAI,
        "https://api.minimaxi.com/v1",
        listOf("MiniMax-M2.7", "MiniMax-M2.5", "MiniMax-M2.1"),
        "https://www.minimaxi.com", "https://platform.minimaxi.com/user-center/basic-information/interface-key"),
    ProviderDef("doubao", "豆包 (字节)", ModelProviderType.OPENAI,
        "https://ark.cn-beijing.volces.com/api/v3",
        listOf("doubao-seed-1-8-251228", "doubao-1-5-pro-32k-250115", "doubao-1-5-vision-pro-32k-250115"),
        "https://www.volcengine.com/product/doubao", "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey"),
    ProviderDef("ai302", "302.AI", ModelProviderType.OPENAI,
        "https://api.302.ai/v1",
        listOf("deepseek-chat", "deepseek-reasoner", "gpt-4o", "claude-sonnet-4-20250514", "gemini-2.5-pro"),
        "https://302.ai", "https://dash.302.ai/apis"),
    ProviderDef("aihubmix", "AiHubMix", ModelProviderType.OPENAI,
        "https://aihubmix.com/v1",
        listOf("gpt-5", "gpt-4o", "claude-sonnet-4-20250514", "gemini-2.5-pro"),
        "https://aihubmix.com", "https://aihubmix.com/token"),
    ProviderDef("burncloud", "BurnCloud", ModelProviderType.OPENAI,
        "https://api.burncloud.com/v1",
        listOf("claude-opus-4-5-20251101", "claude-sonnet-4-5-20250929", "gemini-2.5-flash", "deepseek-chat"),
        "https://burncloud.com", "https://burncloud.com/panel"),
    ProviderDef("ppio", "PPIO", ModelProviderType.OPENAI,
        "https://api.ppio.ai/v1",
        listOf("deepseek/deepseek-v3.2", "minimax/minimax-m2", "qwen/qwen3-235b-a22b-instruct-2507"),
        "https://ppio.ai", "https://ppio.ai/console"),
    // ── 更多 OpenAI 兼容厂商 ──
    ProviderDef("cherryin", "CherryIN", ModelProviderType.OPENAI,
        "https://open.cherryin.cc",
        listOf(), "https://open.cherryin.ai", "https://open.cherryin.ai/console/token"),
    ProviderDef("ocoolai", "ocoolAI", ModelProviderType.OPENAI,
        "https://api.ocoolai.com",
        listOf("deepseek-chat", "deepseek-reasoner", "gpt-4o"),
        "https://one.ocoolai.com", "https://one.ocoolai.com/token"),
    ProviderDef("zai", "Z.ai", ModelProviderType.OPENAI,
        "https://api.z.ai/api/paas/v4",
        listOf("glm-5", "glm-4.7", "glm-4.6", "glm-4.6v"),
        "https://z.ai", "https://z.ai/manage-apikey/apikey-list"),
    ProviderDef("alayanew", "AlayaNew", ModelProviderType.OPENAI,
        "https://deepseek.alayanew.com",
        listOf(), "https://www.alayanew.com", "https://www.alayanew.com/backend/register"),
    ProviderDef("dmxapi", "DMXAPI", ModelProviderType.OPENAI,
        "https://www.dmxapi.cn",
        listOf("Qwen/Qwen2.5-7B-Instruct", "ERNIE-Speed-128K", "gpt-4o"),
        "https://www.dmxapi.cn", "https://www.dmxapi.cn/register"),
    ProviderDef("aionly", "AIOnly", ModelProviderType.OPENAI,
        "https://api.aiionly.com",
        listOf("claude-opus-4-6", "claude-sonnet-4-6", "gpt-5.4", "gemini-3.1-pro-preview"),
        "https://www.aiionly.com", "https://maas.aiionly.com/keyApi"),
    ProviderDef("tokenflux", "TokenFlux", ModelProviderType.OPENAI,
        "https://api.tokenflux.ai/openai/v1",
        listOf("gpt-4.1", "claude-sonnet-4", "gemini-2.5-pro", "deepseek-v3"),
        "https://tokenflux.ai"),
    ProviderDef("cephalon", "Cephalon", ModelProviderType.OPENAI,
        "https://cephalon.cloud/user-center/v1/model",
        listOf("DeepSeek-R1", "DeepSeek-V3", "Qwen3-235B-A22B-Instruct-2507", "kimi-k2-0711-preview"),
        "https://cephalon.cloud", "https://cephalon.cloud/api"),
    ProviderDef("lanyun", "LANYUN (蓝云)", ModelProviderType.OPENAI,
        "https://maas-api.lanyun.net",
        listOf("deepseek-ai/DeepSeek-R1", "deepseek-ai/DeepSeek-V3", "Qwen2.5-72B-Instruct"),
        "https://maas.lanyun.net", "https://maas.lanyun.net/#/system/apiKey"),
    ProviderDef("ph8", "PH8", ModelProviderType.OPENAI,
        "https://ph8.co",
        listOf("deepseek-v3-241226", "deepseek-r1-250120"),
        "https://ph8.co", "https://ph8.co/apiKey"),
    ProviderDef("sophnet", "SophNet", ModelProviderType.OPENAI,
        "https://www.sophnet.com/api/open-apis/v1",
        listOf(), "https://sophnet.com"),
    ProviderDef("minimax-global", "MiniMax Global", ModelProviderType.OPENAI,
        "https://api.minimax.io/v1",
        listOf("MiniMax-M2.7", "MiniMax-M2.5"),
        "https://platform.minimax.io", "https://platform.minimax.io/user-center/basic-information/interface-key"),
    ProviderDef("qiniu", "七牛云", ModelProviderType.OPENAI,
        "https://api.qnaigc.com",
        listOf("deepseek-r1", "deepseek-v3", "qwq-32b", "qwen2.5-72b-instruct"),
        "https://qiniu.com", "https://portal.qiniu.com/ai-inference/api-key"),
    // ── 国内大厂 ──
    ProviderDef("baichuan", "百川智能", ModelProviderType.OPENAI,
        "https://api.baichuan-ai.com",
        listOf(), "https://www.baichuan-ai.com", "https://platform.baichuan-ai.com/console/apikey"),
    ProviderDef("stepfun", "阶跃星辰", ModelProviderType.OPENAI,
        "https://api.stepfun.com",
        listOf(), "https://platform.stepfun.com", "https://platform.stepfun.com/interface-key"),
    ProviderDef("yi", "零一万物", ModelProviderType.OPENAI,
        "https://api.lingyiwanwu.com",
        listOf(), "https://platform.lingyiwanwu.com", "https://platform.lingyiwanwu.com/apikeys"),
    ProviderDef("hunyuan", "腾讯混元", ModelProviderType.OPENAI,
        "https://api.hunyuan.cloud.tencent.com",
        listOf(), "https://cloud.tencent.com/product/hunyuan", "https://console.cloud.tencent.com/hunyuan/api-key"),
    ProviderDef("tencent-cloud-ti", "腾讯云 TI", ModelProviderType.OPENAI,
        "https://api.lkeap.cloud.tencent.com",
        listOf(), "https://cloud.tencent.com/product/ti", "https://console.cloud.tencent.com/lkeap/api"),
    ProviderDef("baidu-cloud", "百度千帆", ModelProviderType.OPENAI,
        "https://qianfan.baidubce.com/v2",
        listOf(), "https://cloud.baidu.com", "https://console.bce.baidu.com/iam/#/iam/apikey/list"),
    ProviderDef("xirang", "天翼云 (息壤)", ModelProviderType.OPENAI,
        "https://wishub-x1.ctyun.cn",
        listOf(), "https://www.ctyun.cn"),
    ProviderDef("modelscope", "ModelScope", ModelProviderType.OPENAI,
        "https://api-inference.modelscope.cn/v1",
        listOf(), "https://modelscope.cn", "https://modelscope.cn/my/myaccesstoken"),
    // ── 国际厂商 ──
    ProviderDef("groq", "Groq", ModelProviderType.OPENAI,
        "https://api.groq.com/openai",
        listOf(), "https://groq.com", "https://console.groq.com/keys"),
    ProviderDef("together", "Together AI", ModelProviderType.OPENAI,
        "https://api.together.xyz",
        listOf(), "https://www.together.ai", "https://api.together.ai/settings/api-keys"),
    ProviderDef("fireworks", "Fireworks AI", ModelProviderType.OPENAI,
        "https://api.fireworks.ai/inference",
        listOf(), "https://fireworks.ai", "https://fireworks.ai/account/api-keys"),
    ProviderDef("nvidia", "NVIDIA NIM", ModelProviderType.OPENAI,
        "https://integrate.api.nvidia.com",
        listOf(), "https://build.nvidia.com"),
    ProviderDef("grok", "Grok (xAI)", ModelProviderType.OPENAI,
        "https://api.x.ai",
        listOf(), "https://x.ai"),
    ProviderDef("hyperbolic", "Hyperbolic", ModelProviderType.OPENAI,
        "https://api.hyperbolic.xyz",
        listOf(), "https://app.hyperbolic.xyz", "https://app.hyperbolic.xyz/settings"),
    ProviderDef("mistral", "Mistral AI", ModelProviderType.OPENAI,
        "https://api.mistral.ai",
        listOf(), "https://mistral.ai", "https://console.mistral.ai/api-keys"),
    ProviderDef("jina", "Jina AI", ModelProviderType.OPENAI,
        "https://api.jina.ai",
        listOf(), "https://jina.ai"),
    ProviderDef("perplexity", "Perplexity", ModelProviderType.OPENAI,
        "https://api.perplexity.ai",
        listOf(), "https://perplexity.ai", "https://www.perplexity.ai/settings/api"),
    ProviderDef("infini", "Infini", ModelProviderType.OPENAI,
        "https://cloud.infini-ai.com/maas",
        listOf(), "https://cloud.infini-ai.com", "https://cloud.infini-ai.com/iam/secret/key"),
    ProviderDef("poe", "Poe", ModelProviderType.OPENAI,
        "https://api.poe.com/v1",
        listOf(), "https://poe.com", "https://poe.com/api/keys"),
    ProviderDef("longcat", "LongCat", ModelProviderType.OPENAI,
        "https://api.longcat.chat/openai",
        listOf(), "https://longcat.chat", "https://longcat.chat/platform/api_keys"),
    ProviderDef("huggingface", "Hugging Face", ModelProviderType.OPENAI,
        "https://router.huggingface.co/v1",
        listOf(), "https://huggingface.co", "https://huggingface.co/settings/tokens"),
    ProviderDef("cerebras", "Cerebras AI", ModelProviderType.OPENAI,
        "https://api.cerebras.ai/v1",
        listOf(), "https://www.cerebras.ai", "https://cloud.cerebras.ai"),
    ProviderDef("voyageai", "Voyage AI", ModelProviderType.OPENAI,
        "https://api.voyageai.com",
        listOf(), "https://www.voyageai.com", "https://dashboard.voyageai.com/organization/api-keys"),
    ProviderDef("github", "GitHub Models", ModelProviderType.OPENAI,
        "https://models.github.ai/inference",
        listOf("gpt-4o"), "https://github.com/marketplace/models", "https://github.com/settings/tokens"),
    ProviderDef("copilot", "GitHub Copilot", ModelProviderType.OPENAI,
        "https://api.githubcopilot.com",
        listOf())
)
